# Assignment 2 IRS

Information retrieval is the process of obtaining information system resources that are relevant to an information need from a collection of those resources. The core purpose of this assignment is to give you the flavor of IRS. You need to follow some steps listed below and in the end, you'll be able to build your own small IRS. So, let's start.

In [9]:
# required imports
import numpy as np
import fnmatch
import os


Suppose we have 3 files containing data :

### File Contents

!["This is my book" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f1.png?raw=true)
!["This is my pen" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f2.png?raw=true)
!["This is book is intersting" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f3.png?raw=true)

# Step 1 Create Files with Dummy data

You have to create few files with dummy data of your own choice as shown above.

# Step 2 Traverse Directories

 Now, You have to traverse the directories and store all the files into a dict type variable(files_dict). 

In [10]:
# Here we have intialized some variables, you can add more if required.

file_count = 0             # file_count to count number of files
files_dict = {}            # files_dic to store count of every file    
unique_word_set = set()    # unique_word_set to store all the unique words in a set
dir_path = "C:\\Users\\Fatima\\Desktop\\files"




In [18]:
#Your code starts here

#we are exploring dir_path using os.walk fuction,it helps to explore directory and its sub directories in it
#root is current dirctory path,dirs is subdirectories inside directory and files are files inside it
for root, dirs, files in os.walk(dir_path):
    for i in files:
        if i.endswith(".txt"):   #we are lookinf for the file by using its extnsion
            if i not in files_dict:
                files_dict[i] = 1   #if it is not in directory add it with count of one,else just incriment the count
            else:
                files_dict[i] += 1
                file_count += 1


print("Total number of files:", file_count)
print("Files dictionary:", files_dict)
#Your code ends here       

Total number of files: 15
Files dictionary: {'file1.txt': 6, 'file2.txt': 6, 'file3.txt': 6}


Displaying the count of files.

In [14]:
print("\nTotal Number  of files\n", file_count)


Total Number  of files
 3


Displaying Dictionary containing all files.

In [11]:
print("\nDictionary containing  files\n", files_dict)


Dictionary containing  files
 {'file1.txt': 1, 'file2.txt': 1, 'file3.txt': 1}


# Step 3 Extract Unique Vocabulary

write code to print all the unique words in every file and store them in a set

In [20]:
#Your code starts here    

unique_word_set = set()

for file in ['file1.txt', 'file2.txt', 'file3.txt']:  #iterate throgh files

    file_path = os.path.join(dir_path, file) #this function creates a full file path by joining directory path and filename
    try:
       
        with open(file_path, 'r') as file:  
            content = file.read()
            
            words = content.split()
            unique_word_set.update(words)
    except FileNotFoundError:
        print("File not found")


print("Unique words in all files:", unique_word_set)
print("Total number of files:", len(['file1.txt', 'file2.txt', 'file3.txt']))


#Your code ends here

Unique words in all files: {'mobile', 'this', 'is', 'tree', 'a', 'bag'}
Total number of files: 3


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o1.png?raw=true)


# Step 4 Create Term Document Matrix

Create Term-Doc-matrix using Bag of word approach.and display its contents initially and finally.

- Create Term doc matrix such that colmns will be unique words and all the files will be rows
- Write code to count all the unique words appearances in all the files and store it in a dictionary for words 

In [49]:
#Your code starts here    


unique_words = {}       
files_dict = {}                   
for root, dirs, files in os.walk(dir_path):
    for file in files:
        if file.endswith(".txt"):
            file_path = os.path.join(root, file)
            files_dict[file] = len(files_dict)
            with open(file_path, 'r') as filee:
                text = filee.read()
                words = text.split()
                for word in words:
                    if word not in unique_words:   
                        unique_words[word] = len(unique_words)
term_doc_matrix = np.zeros((len(files_dict), len(unique_words)))   
print(term_doc_matrix)
print("Unique Words:")
print(unique_words)
print("Files:")
print(files_dict)

  

   #Your code ends here

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Unique Words:
{'this': 0, 'is': 1, 'a': 2, 'mobile': 3, 'bag': 4, 'tree': 5}
Files:
{'file1.txt': 0, 'file2.txt': 1, 'file3.txt': 2}


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o2.png?raw=true)

In [2]:

current_directory = os.getcwd()

print(f"Current working directory: {current_directory}")

Current working directory: C:\Users\Fatima\Downloads


# Step 5 Fill Term Document Matrix

- Fill the term doc matrix by checking if the unique word exists in a file or not
- If it exists then substitute a 1 in term_doc_matrix (eg : TERM_DOC_MATRIX[file][word] = 1 ) 
- Do the same for all the files present in the directory

In [52]:
#Your code starts here    
  
for f,file in files_dict.items():
     with open(file_path, 'r') :
        for w in words:
            if w in unique_words:   
                word = unique_words[w]
                term_doc_matrix[file][word] = 1    
print("Term-Document Matrix:")
print(term_doc_matrix)
print("Dictionary of Unique Words:")
print(unique_words)
#Your code ends here

Term-Document Matrix:
[[1. 1. 1. 0. 0. 1.]
 [1. 1. 1. 0. 0. 1.]
 [1. 1. 1. 0. 0. 1.]]
Dictionary of Unique Words:
{'this': 0, 'is': 1, 'a': 2, 'mobile': 3, 'bag': 4, 'tree': 5}


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o4.png?raw=true)


# Step 6 Ask for a user Query

For user query make a column vector of length of all the unique words present in a set

In [54]:
#Your code starts here    


word_set = {'1', '2', '3', '4', '5', '6'}

colVector = np.zeros((len(word_set), 1))
print("ColVector initially:")
print(colVector)


#Your code ends here

ColVector initially:
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o5.png?raw=true)


In [56]:
#query = input("\nWrite something for searching  ")
# Check every word of query if it exists in the set of unique words or not
# If exists then increment the count of that word in word dictionary
#implemented below

In [68]:
#Your code starts here    



print("Unique words set:", unique_words_set)
query = input("\nWrite something for searching: ")


colVector = np.zeros((len(unique_words_set), 1))   
query_words = query.split()  

for word in query_words:  
    if word in unique_words_set:       
        unique_index = list(unique_words_set).index(word)
        colVector[unique_index] += 1

print("ColVector after query:")
print(colVector)



Unique words set: {'mobile', 'this', 'is', 'tree', 'a', 'bag'}

Write something for searching: this
ColVector after query:
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o6.png?raw=true)


# Step 7 Display Resultant Vector

Display 
1. Resultant vector.
2. Max value in resultant vector.
3. Index of max value in resultant vector.


In [75]:

#resultant vector
resultant_vector = np.sum(term_doc_matrix, axis=0)  


value = np.max(resultant_vector)
index = np.argmax(resultant_vector)

# Display the resultant vector, max value, and max index
print("Resultant vector:")
print(resultant_vector)
print("max index")
print(index)
print("max value")
print(value)




Resultant vector:
[3. 3. 3. 0. 0. 3.]
max index
0
max value
3.0


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o7.png?raw=true)


# Step 8 Display the contents of file


Write the code to identify the file_name having maximum value in the resultant vector and display its contents.

In [80]:
#Your code starts here    

max_index = np.argmax(resultant_vector)   

max_file = list(files_dict.keys())[max_index]  


file_path = os.path.join(dir_path, max_file)  
with open(file_path, 'r') as file:
     contents = file.read()

print("File contents of",max_file)
print(contents)





File contents of file1.txt
this is a mobile


Congratulations Now you are able to build your own small IRS.