# Assignment 2 IRS - With Synonyms

Information retrieval is the process of obtaining information system resources that are relevant to an information need from a collection of those resources. The core purpose of this assignment is to give you the flavor of IRS. You need to follow some steps listed below and in the end, you'll be able to build your own small IRS. So, let's start.

In [1]:
# required imports
import numpy as np
import fnmatch
import os


Suppose we have 3 files containing data :

### File Contents

!["This is my book" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f1.png?raw=true)
!["This is my pen" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f2.png?raw=true)
!["This is book is intersting" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f3.png?raw=true)

# Step 1 Create Files with Dummy data

You have to create few files with dummy data of your own choice as shown above.

# Step 2 Traverse Directories

 Now, You have to traverse the directories and store all the files into a dict type variable(files_dict). 

In [2]:
# Here we have initialized some variables, you can add more if required.

file_count = 0             # file_count to count number of files
files_dict = {}            # files_dic to store count of every file    
unique_word_set = set()    # unique_word_set to store all the unique words in a set
dir_path = "C:\\Users\\Fatima\\Desktop\\files"


In [4]:
#Your code starts here   
#Your code starts here

#we are exploring dir_path using os.walk fuction,it helps to explore directory and its sub directories in it
#root is current dirctory path,dirs is subdirectories inside directory and files are files inside it
for root, dirs, files in os.walk(dir_path):
    for i in files:
        if i.endswith(".txt"):   
            if i not in files_dict:
                files_dict[i] = 1    
            else:
                files_dict[i] += 1
                file_count += 1

print("Total number of files:", file_count)
print("Files dictionary:", files_dict)
     


#Your code ends here       

Total number of files: 4
Files dictionary: {'file1.txt': 2, 'file2.txt': 2, 'file3.txt': 2, 'synonyms.txt': 2}


Displaying the count of files.

In [5]:
print("\nTotal Number  of files\n", file_count)


Total Number  of files
 4


Displaying Dictionary containing all files.

In [6]:
print("\nDictionary containing  files\n", files_dict)


Dictionary containing  files
 {'file1.txt': 2, 'file2.txt': 2, 'file3.txt': 2, 'synonyms.txt': 2}


# Step 3 Extract Unique Vocabulary

write code to print all the unique words in every file and store them in a set

In [7]:
#Your code starts here    


unique_word_set = set()

for file in ['file1.txt', 'file2.txt', 'file3.txt']:   

    file_path = os.path.join(dir_path, file)  
    try:
       
        with open(file_path, 'r') as file:  
            content = file.read()
            
            words = content.split()
            unique_word_set.update(words)
    except FileNotFoundError:
        print("File not found")


print("Unique words in all files:", unique_word_set)
print("Total number of files:", len(['file1.txt', 'file2.txt', 'file3.txt']))



#Your code ends here

Unique words in all files: {'a', 'mobile', 'this', 'is', 'bag', 'tree'}
Total number of files: 3


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o1.png?raw=true)


# Step 4 Create Term Document Matrix

Create Term-Doc-matrix using Bag of word approach.and display its contents initially and finally.

1. Create Term doc matrix such that colmns will be unique words and all the files will be rows
2. Write code to count all the unique words appearances in all the files and store it in a dictionary for words 

In [8]:
#Your code starts here


unique_words = {}       
files_dict = {}                    
for root, dirs, files in os.walk(dir_path):
    for file in files:
        if file.endswith(".txt"):
            file_path = os.path.join(root, file)
            files_dict[file] = len(files_dict)
            with open(file_path, 'r') as filee:
                text = filee.read()
                words = text.split()
                for word in words:
                    if word not in unique_words:  
                        unique_words[word] = len(unique_words)
term_doc_matrix = np.zeros((len(files_dict), len(unique_words)))   
print(term_doc_matrix)
print("Unique Words:")
print(unique_words)
print("Files:")
print(files_dict)

  

#Your code ends here

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
Unique Words:
{'this': 0, 'is': 1, 'a': 2, 'mobile': 3, 'bag': 4, 'tree': 5, 'is,am,are,he,she,her,this,mobiles': 6}
Files:
{'file1.txt': 0, 'file2.txt': 1, 'file3.txt': 2, 'synonyms.txt': 3}


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o2.png?raw=true)

# Step 5 Fill Term Document Matrix

1. Fill the term doc matrix by checking if the unique word exists in a file or not
2. If it exists then substitute a 1 in term_doc_matrix (eg : TERM_DOC_MATRIX[file][word] = 1 ) 
3. Do the same for all the files present in the directory

In [9]:
#Your code starts here    

for f,file in files_dict.items():
     with open(file_path, 'r') :
        for w in words:
            if w in unique_words:  #we are taking unique word index and file index and storing 1 
                word = unique_words[w]
                term_doc_matrix[file][word] = 1    
print("Term-Document Matrix:")
print(term_doc_matrix)
print("Dictionary of Unique Words:")
print(unique_words)
#Your code ends here


Term-Document Matrix:
[[0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]]
Dictionary of Unique Words:
{'this': 0, 'is': 1, 'a': 2, 'mobile': 3, 'bag': 4, 'tree': 5, 'is,am,are,he,she,her,this,mobiles': 6}


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o4.png?raw=true)


# Step 6 Ask for a user Query

For user query make a column vector of length of all the unique words present in a set

In [10]:
#Your code starts here    

word_set = {'1', '2', '3', '4', '5', '6'}

colVector = np.zeros((len(word_set), 1))
print("ColVector initially:")
print(colVector)


#Your code ends here

ColVector initially:
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o5.png?raw=true)


In [10]:
query = input("\nWrite something for searching:  ")
print("Query is:", query)


Write something for searching:  mobile
Query is: mobile


### Expected Output

![Expected Output of query](images/Query.png)

# Step 7 Load Synonyms

In [26]:


synonym_file_path ="C:\\Users\\Fatima\\Desktop\\files\\synonyms.txt"
synonyms_dict = {}  # Dictionary to store synonyms

if os.path.exists(synonym_file_path):
    with open(synonym_file_path, 'r') as file:
        lines = file.readlines()
        for line in lines:
            words = line.strip().split(',')
            main_word = words[0]
            synonyms = words[1:]
            synonyms_dict[main_word] = synonyms
else:
    print("Synonym file does not exist!")


    
print("\nSynonyms Dictionary\n")
print(synonyms_dict)





Synonyms Dictionary

{'is': ['am', 'are', 'he', 'she', 'her', 'this', 'mobiles']}


### Expected Output

![Synonym Dict Example](images\Synonym_dict.png)

# Step 8 Extend User Query

In [27]:

user_query = input("Enter your query: ").split()  #taking user input and spliting it
expanded_query = []
for word in user_query:
    expanded_query.append(word)
    if word in synonyms_dict:
        expanded_query.extend(synonyms_dict[word])

print("Expanded Query")
print(expanded_query)

Enter your query: hi
Expanded Query
['hi']


### Expected Output

![Extended Query](images\Expanded_Query.png)

Now work with extended query and find the relevant documents.

In [ ]:
# Check every word of query if it exists in the set of unique words or not
# If exists then increment the count of that word in word dictionary


In [24]:

word_dict = {word: 0 for word in expanded_query}

# Your code starts here
for word in expanded_query:
    if word in unique_words:
        word_dict[word] += 1
# Your code ends here

print("\nWord Dictionary:")
print(word_dict)






Word Dictionary:
{'hi': 0}


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o6.png?raw=true)


# Step 7 Display Resultant Vector

Display 
1. Resultant vector.
2. Max value in resultant vector.
3. Index of max value in resultant vector.


In [28]:
#Your code starts here  

resultant_vector = np.array([word_dict[word] for word in expanded_query])

print("Resultant Vector:")
print(resultant_vector)
print("Max value in resultant vector:", np.max(resultant_vector))
print("Index of max value in resultant vector:", np.argmax(resultant_vector))


#Your code ends here

Resultant Vector:
[0]
Max value in resultant vector: 0
Index of max value in resultant vector: 0


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o7.png?raw=true)


# Step 8 Display the contents of file


Write the code to identify the file_name having maximum value in the resultant vector and display its contents.

In [31]:
#Your code starts here    


max_index = np.argmax(resultant_vector)  

max_file = list(files_dict.keys())[max_index] 


file_path = os.path.join(dir_path, max_file)  
with open(file_path, 'r') as file:
     contents = file.read()

print("File contents of",max_file)
print(contents)




#Your code ends here

File contents of file1.txt
this is a mobile


Congratulations Now you are able to build your own small IRS which can work even if query does not have exact same words.